### PR TITLE
Big changes all around

### PR DESCRIPTION
**Pull request by saibotsivad**
- Changed a bunch of things related to the site layout, hopefully making it easier to read.
- Switched from a single-document layout to a multiple-page layout. This made it easier to write, but eventually if I can simplify it down a bit more I'll revert back to a single page.
- Simplified a lot of the communication stuff, stripping out functionality that didn't need to be core.
- Made the communication documents network agnostic.
- Specified the session key exchange via Diffie-Helman a bit differently so it's network agnostic as well.

### CODE REVIEW

**Comment by jmhobbs** [comment]
I think this created some broken links.  Like in [signed-tar-npm](https://github.com/sdmp/signed-tar-npm/blame/master/README.md#L4)

**Comment by saibotsivad** [comment]
Oh hey thanks! I'll get those fixed this week. I've got some vacation time coming up, so I hope to finally make a usable demo implementation!

On June 16, 2015 11:24:55 AM CDT, John Hobbs notifications@github.com wrote:

> I think this created some broken links.  Like in
> [signed-tar-npm](https://github.com/sdmp/signed-tar-npm/blame/master/README.md#L4)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sdmp/sdmp.github.io/pull/4#issuecomment-112487591

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by saibotsivad** [comment]
The [signed tar](https://github.com/sdmp/signed-tar) idea turned out to be way less useful than the [signed YAML](http://github.com/sdmp/signed-yaml) idea, at least for the core SDMP specs, so it's no longer part of the core protocol.

Because of this, I had actually removed the Github Pages (`gh-pages` branch) for the signed tar specs a while back, but had forgotten to update the links. Sorry about that, and thanks for noticing!

I think the signed tar idea is still useful for an implementation of the SDMP that I have planned, but for now it's on my back burner. If you use it, or have a potential use for it, I'd love to chat with you about how to make it better!

**Comment by jmhobbs** [comment]
Whoops! My bad, I was poking around and saw the broken link, assumed it was related to these changes.

I don't actually use the tar, was just wandering through the repos. :)

**Pull request merged**
